NETOBSERV-1020 Fix empty namespace list
observatorium/opa-openshift pull request #18
Opened 2023-05-05 13:09 UTC by jotak

Because of the "strings.Join" performed on the namespace list, an empty list is interpreted as an empty namespace. While this might be ok for logging, it is not for netobserv because empty namespaces are a thing (e.g. host network traffic is non-namespaced)

~~Dependent PR: https://github.com/observatorium/api/pull/512~~

2023-05-05 13:15 UTC, jotak commented
This would need to be backported on 5.7

2023-05-05 13:38 UTC, jotak commented
Hmm is this code also affecting the write path? I'm currently trying to test, but can't get anything written into loki...

2023-05-08 08:58 UTC, periklis requested changes
The proposed fix breaks actually the present OpenShift Logging, i.e. users w/o assigned namespaces immediately can see all the namespaces. The behavior of `strings.Join` although not too explicit was intentional to disallow a privilege escalation when creating new users for example.

IMHO this is another good showcase that the openshift-logging and openshift-network tenancy model differ (i.e. the other one is the matcher op). Thus we need to make the empty namespace behavior something you configure per tenancy model in the Loki Operator. I suggest we expose another CLI flag for this. WDYT?

2023-05-09 10:21 UTC, jotak commented
@periklis 
as discussed: the PR was amended so that it doesn't require any change on the API side.
Now, there's a distinction between read & write path. Matchers are set up only for the read path, and failing due to empty namespaces list only occurs for read.

2023-05-23 18:47 UTC, periklis approved these changes

2023-05-24 09:46 UTC, periklis approved these changes

2023-05-24 09:46 UTC, periklis commented on internal/authorizer/authorizer.go
> +			// Explicitly disallow user query with no allowed namespaces
```suggestion
			// Explicitly disallow a user query with no allowed namespaces
```

2023-05-24 09:53 UTC, merged